// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CoreService struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as fs$0 from "./internal/fs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as structs$0 from "./internal/structs/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAccount(accountId: string): $CancellablePromise<$models.AccountWithUnlockStatus | null> {
    return $Call.ByID(2445503429, accountId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAccounts returns the accounts for the application.
 */
export function GetAccounts(): $CancellablePromise<($models.AccountWithUnlockStatus | null)[]> {
    return $Call.ByID(748851074).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetItemOverview(itemId: string): $CancellablePromise<$models.DecryptedVaultItemOverview | null> {
    return $Call.ByID(1670617126, itemId).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetVaultItemDetails(itemId: string): $CancellablePromise<$models.DecryptedVaultItemDetails | null> {
    return $Call.ByID(1775651925, itemId).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetVaultMetadata returns the vault metadata for the given vault ID.
 */
export function GetVaultMetadata(vaultId: string): $CancellablePromise<structs$0.VaultMetadata | null> {
    return $Call.ByID(2085091987, vaultId).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * Initialize initializes the application with the given options. If the application
 * is already initialized, it does nothing.
 */
export function Initialize(opts: fs$0.InitOptions): $CancellablePromise<void> {
    return $Call.ByID(176613780, opts);
}

/**
 * IsInitialized returns whether the application has been initialized
 */
export function IsInitialized(): $CancellablePromise<boolean> {
    return $Call.ByID(2350081508);
}

export function IsLocked(): $CancellablePromise<boolean> {
    return $Call.ByID(1874315844);
}

export function ListAllItemOverviews(): $CancellablePromise<($models.DecryptedVaultItemOverview | null)[]> {
    return $Call.ByID(3858392174).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListVaultItemOverviews(vaultId: string): $CancellablePromise<($models.DecryptedVaultItemOverview | null)[]> {
    return $Call.ByID(2287033531, vaultId).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetVaultMetadatas returns the vault metadata for the given account IDs.
 */
export function ListVaultMetadatas(accountIds: string[]): $CancellablePromise<(structs$0.VaultMetadata | null)[]> {
    return $Call.ByID(2047389568, accountIds).then(($result: any) => {
        return $$createType10($result);
    });
}

export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(769314425);
}

export function TryUnlock(password: string): $CancellablePromise<void> {
    return $Call.ByID(2015788031, password);
}

// Private type creation functions
const $$createType0 = $models.AccountWithUnlockStatus.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.DecryptedVaultItemOverview.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.DecryptedVaultItemDetails.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = structs$0.VaultMetadata.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType4);
const $$createType10 = $Create.Array($$createType8);
