// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cryptolib$0 from "../cryptolib/models.js";

export class AccountWithUnlockStatus {
    "id": string;
    "user_email": string;
    "user_first_name": string;
    "user_last_name": string;
    "secret_key": cryptolib$0.SecretKey | null;
    "is_unlocked": boolean;

    /** Creates a new AccountWithUnlockStatus instance. */
    constructor($$source: Partial<AccountWithUnlockStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("user_email" in $$source)) {
            this["user_email"] = "";
        }
        if (!("user_first_name" in $$source)) {
            this["user_first_name"] = "";
        }
        if (!("user_last_name" in $$source)) {
            this["user_last_name"] = "";
        }
        if (!("secret_key" in $$source)) {
            this["secret_key"] = null;
        }
        if (!("is_unlocked" in $$source)) {
            this["is_unlocked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountWithUnlockStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AccountWithUnlockStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountWithUnlockStatus($$parsedSource as Partial<AccountWithUnlockStatus>);
    }
}

export class DecryptedVaultItemDetails {
    "item_id": string;
    "vault_id": string;
    "created_at": string;
    "updated_at": string;
    "encrypted_details": cryptolib$0.JWE | null;
    "username": string;
    "password": string;
    "notes": string;

    /** Creates a new DecryptedVaultItemDetails instance. */
    constructor($$source: Partial<DecryptedVaultItemDetails> = {}) {
        if (!("item_id" in $$source)) {
            this["item_id"] = "";
        }
        if (!("vault_id" in $$source)) {
            this["vault_id"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("encrypted_details" in $$source)) {
            this["encrypted_details"] = null;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DecryptedVaultItemDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): DecryptedVaultItemDetails {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("encrypted_details" in $$parsedSource) {
            $$parsedSource["encrypted_details"] = $$createField4_0($$parsedSource["encrypted_details"]);
        }
        return new DecryptedVaultItemDetails($$parsedSource as Partial<DecryptedVaultItemDetails>);
    }
}

export class DecryptedVaultItemOverview {
    "item_id": string;
    "vault_id": string;
    "created_at": string;
    "updated_at": string;
    "encrypted_overview": cryptolib$0.JWE | null;
    "title": string;
    "url": string;

    /** Creates a new DecryptedVaultItemOverview instance. */
    constructor($$source: Partial<DecryptedVaultItemOverview> = {}) {
        if (!("item_id" in $$source)) {
            this["item_id"] = "";
        }
        if (!("vault_id" in $$source)) {
            this["vault_id"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("encrypted_overview" in $$source)) {
            this["encrypted_overview"] = null;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DecryptedVaultItemOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): DecryptedVaultItemOverview {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("encrypted_overview" in $$parsedSource) {
            $$parsedSource["encrypted_overview"] = $$createField4_0($$parsedSource["encrypted_overview"]);
        }
        return new DecryptedVaultItemOverview($$parsedSource as Partial<DecryptedVaultItemOverview>);
    }
}

// Private type creation functions
const $$createType0 = cryptolib$0.JWE.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
