// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class InitOptions {
    "FirstName": string;
    "LastName": string;
    "Email": string;
    "Password": string;

    /** Creates a new InitOptions instance. */
    constructor($$source: Partial<InitOptions> = {}) {
        if (!("FirstName" in $$source)) {
            this["FirstName"] = "";
        }
        if (!("LastName" in $$source)) {
            this["LastName"] = "";
        }
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InitOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): InitOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InitOptions($$parsedSource as Partial<InitOptions>);
    }
}
