// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class VaultMetadata {
    "account_id": string;
    "vault_id": string;
    "name": string;
    "description": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new VaultMetadata instance. */
    constructor($$source: Partial<VaultMetadata> = {}) {
        if (!("account_id" in $$source)) {
            this["account_id"] = "";
        }
        if (!("vault_id" in $$source)) {
            this["vault_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultMetadata {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultMetadata($$parsedSource as Partial<VaultMetadata>);
    }
}
