// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export type ContentType = string;

export class JWE {
    /**
     * ContentType indicates the type of the wrapped content
     */
    "cty": ContentType;

    /**
     * EncryptedData is the encrypted key data
     */
    "data": string;

    /**
     * IV is the initialization vector or nonce used during encryption (if applicable)
     */
    "iv"?: string;

    /**
     * EncryptionAlg is the algorithm used to encrypt the key
     */
    "enc": string;

    /**
     * Hint at which key was used to wrap (encrypt) this key
     */
    "kid": string;

    /**
     * Optional header for PBKDF2 salt
     */
    "p2s"?: string;

    /**
     * Optional header for PBKDF2 rounds
     */
    "p2c"?: number | null;

    /** Creates a new JWE instance. */
    constructor($$source: Partial<JWE> = {}) {
        if (!("cty" in $$source)) {
            this["cty"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("enc" in $$source)) {
            this["enc"] = "";
        }
        if (!("kid" in $$source)) {
            this["kid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JWE instance from a string or object.
     */
    static createFrom($$source: any = {}): JWE {
        const $$createField1_0 = $Create.ByteSlice;
        const $$createField2_0 = $Create.ByteSlice;
        const $$createField5_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        if ("iv" in $$parsedSource) {
            $$parsedSource["iv"] = $$createField2_0($$parsedSource["iv"]);
        }
        if ("p2s" in $$parsedSource) {
            $$parsedSource["p2s"] = $$createField5_0($$parsedSource["p2s"]);
        }
        return new JWE($$parsedSource as Partial<JWE>);
    }
}

export type SecretKey = any;
