// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {structs} from '../models';
import {fs} from '../models';

export function GetAccounts():Promise<Array<main.AccountWithUnlockStatus>>;

export function GetAllVaultItemOverviews():Promise<Array<main.DecryptedVaultItemOverview>>;

export function GetVaultItemDetails(arg1:string,arg2:string):Promise<main.DecryptedVaultItemDetails>;

export function GetVaultItemOverviews(arg1:string):Promise<Array<main.DecryptedVaultItemOverview>>;

export function GetVaultMetadatas(arg1:Array<string>):Promise<Array<structs.VaultMetadata>>;

export function Greet(arg1:string):Promise<string>;

export function Initialize(arg1:fs.InitOptions):Promise<void>;

export function IsInitialized():Promise<boolean>;

export function IsLocked():Promise<boolean>;

export function Lock():Promise<void>;

export function TryUnlock(arg1:string):Promise<void>;
