// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAllVaultItemOverviews() {
  return window['go']['main']['App']['GetAllVaultItemOverviews']();
}

export function GetVaultItemDetails(arg1, arg2) {
  return window['go']['main']['App']['GetVaultItemDetails'](arg1, arg2);
}

export function GetVaultItemOverviews(arg1) {
  return window['go']['main']['App']['GetVaultItemOverviews'](arg1);
}

export function GetVaultMetadatas(arg1) {
  return window['go']['main']['App']['GetVaultMetadatas'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Initialize(arg1) {
  return window['go']['main']['App']['Initialize'](arg1);
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function IsLocked() {
  return window['go']['main']['App']['IsLocked']();
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function TryUnlock(arg1) {
  return window['go']['main']['App']['TryUnlock'](arg1);
}
