/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LockRouteImport } from './routes/lock'
import { Route as InitializeRouteImport } from './routes/initialize'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedVaultsRouteImport } from './routes/_authenticated/vaults'
import { Route as AuthenticatedVaultsIdRouteImport } from './routes/_authenticated/vaults/$id'
import { Route as AuthenticatedVaultsIdItemsItemIdRouteImport } from './routes/_authenticated/vaults/$id/items.$itemId'

const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const InitializeRoute = InitializeRouteImport.update({
  id: '/initialize',
  path: '/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVaultsRoute = AuthenticatedVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVaultsIdRoute = AuthenticatedVaultsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedVaultsRoute,
} as any)
const AuthenticatedVaultsIdItemsItemIdRoute =
  AuthenticatedVaultsIdItemsItemIdRouteImport.update({
    id: '/items/$itemId',
    path: '/items/$itemId',
    getParentRoute: () => AuthenticatedVaultsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/initialize': typeof InitializeRoute
  '/lock': typeof LockRoute
  '/vaults': typeof AuthenticatedVaultsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/vaults/$id': typeof AuthenticatedVaultsIdRouteWithChildren
  '/vaults/$id/items/$itemId': typeof AuthenticatedVaultsIdItemsItemIdRoute
}
export interface FileRoutesByTo {
  '/initialize': typeof InitializeRoute
  '/lock': typeof LockRoute
  '/vaults': typeof AuthenticatedVaultsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/vaults/$id': typeof AuthenticatedVaultsIdRouteWithChildren
  '/vaults/$id/items/$itemId': typeof AuthenticatedVaultsIdItemsItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/initialize': typeof InitializeRoute
  '/lock': typeof LockRoute
  '/_authenticated/vaults': typeof AuthenticatedVaultsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/vaults/$id': typeof AuthenticatedVaultsIdRouteWithChildren
  '/_authenticated/vaults/$id/items/$itemId': typeof AuthenticatedVaultsIdItemsItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/initialize'
    | '/lock'
    | '/vaults'
    | '/'
    | '/vaults/$id'
    | '/vaults/$id/items/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/initialize'
    | '/lock'
    | '/vaults'
    | '/'
    | '/vaults/$id'
    | '/vaults/$id/items/$itemId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/initialize'
    | '/lock'
    | '/_authenticated/vaults'
    | '/_authenticated/'
    | '/_authenticated/vaults/$id'
    | '/_authenticated/vaults/$id/items/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  InitializeRoute: typeof InitializeRoute
  LockRoute: typeof LockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initialize': {
      id: '/initialize'
      path: '/initialize'
      fullPath: '/initialize'
      preLoaderRoute: typeof InitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults': {
      id: '/_authenticated/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof AuthenticatedVaultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults/$id': {
      id: '/_authenticated/vaults/$id'
      path: '/$id'
      fullPath: '/vaults/$id'
      preLoaderRoute: typeof AuthenticatedVaultsIdRouteImport
      parentRoute: typeof AuthenticatedVaultsRoute
    }
    '/_authenticated/vaults/$id/items/$itemId': {
      id: '/_authenticated/vaults/$id/items/$itemId'
      path: '/items/$itemId'
      fullPath: '/vaults/$id/items/$itemId'
      preLoaderRoute: typeof AuthenticatedVaultsIdItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedVaultsIdRoute
    }
  }
}

interface AuthenticatedVaultsIdRouteChildren {
  AuthenticatedVaultsIdItemsItemIdRoute: typeof AuthenticatedVaultsIdItemsItemIdRoute
}

const AuthenticatedVaultsIdRouteChildren: AuthenticatedVaultsIdRouteChildren = {
  AuthenticatedVaultsIdItemsItemIdRoute: AuthenticatedVaultsIdItemsItemIdRoute,
}

const AuthenticatedVaultsIdRouteWithChildren =
  AuthenticatedVaultsIdRoute._addFileChildren(
    AuthenticatedVaultsIdRouteChildren,
  )

interface AuthenticatedVaultsRouteChildren {
  AuthenticatedVaultsIdRoute: typeof AuthenticatedVaultsIdRouteWithChildren
}

const AuthenticatedVaultsRouteChildren: AuthenticatedVaultsRouteChildren = {
  AuthenticatedVaultsIdRoute: AuthenticatedVaultsIdRouteWithChildren,
}

const AuthenticatedVaultsRouteWithChildren =
  AuthenticatedVaultsRoute._addFileChildren(AuthenticatedVaultsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedVaultsRoute: typeof AuthenticatedVaultsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedVaultsRoute: AuthenticatedVaultsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  InitializeRoute: InitializeRoute,
  LockRoute: LockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
