/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LockRouteImport } from './routes/lock'
import { Route as InitializeRouteImport } from './routes/initialize'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as AuthenticatedLayoutItemFilterRouteImport } from './routes/_authenticated/_layout.$itemFilter'
import { Route as AuthenticatedLayoutItemFilterItemIdRouteImport } from './routes/_authenticated/_layout.$itemFilter.$itemId'

const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const InitializeRoute = InitializeRouteImport.update({
  id: '/initialize',
  path: '/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLayoutItemFilterRoute =
  AuthenticatedLayoutItemFilterRouteImport.update({
    id: '/$itemFilter',
    path: '/$itemFilter',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutItemFilterItemIdRoute =
  AuthenticatedLayoutItemFilterItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AuthenticatedLayoutItemFilterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/initialize': typeof InitializeRoute
  '/lock': typeof LockRoute
  '/$itemFilter': typeof AuthenticatedLayoutItemFilterRouteWithChildren
  '/$itemFilter/$itemId': typeof AuthenticatedLayoutItemFilterItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/initialize': typeof InitializeRoute
  '/lock': typeof LockRoute
  '/$itemFilter': typeof AuthenticatedLayoutItemFilterRouteWithChildren
  '/$itemFilter/$itemId': typeof AuthenticatedLayoutItemFilterItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/initialize': typeof InitializeRoute
  '/lock': typeof LockRoute
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/_layout/$itemFilter': typeof AuthenticatedLayoutItemFilterRouteWithChildren
  '/_authenticated/_layout/$itemFilter/$itemId': typeof AuthenticatedLayoutItemFilterItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/initialize'
    | '/lock'
    | '/$itemFilter'
    | '/$itemFilter/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/initialize' | '/lock' | '/$itemFilter' | '/$itemFilter/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/initialize'
    | '/lock'
    | '/_authenticated/_layout'
    | '/_authenticated/_layout/$itemFilter'
    | '/_authenticated/_layout/$itemFilter/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  InitializeRoute: typeof InitializeRoute
  LockRoute: typeof LockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initialize': {
      id: '/initialize'
      path: '/initialize'
      fullPath: '/initialize'
      preLoaderRoute: typeof InitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_layout/$itemFilter': {
      id: '/_authenticated/_layout/$itemFilter'
      path: '/$itemFilter'
      fullPath: '/$itemFilter'
      preLoaderRoute: typeof AuthenticatedLayoutItemFilterRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/$itemFilter/$itemId': {
      id: '/_authenticated/_layout/$itemFilter/$itemId'
      path: '/$itemId'
      fullPath: '/$itemFilter/$itemId'
      preLoaderRoute: typeof AuthenticatedLayoutItemFilterItemIdRouteImport
      parentRoute: typeof AuthenticatedLayoutItemFilterRoute
    }
  }
}

interface AuthenticatedLayoutItemFilterRouteChildren {
  AuthenticatedLayoutItemFilterItemIdRoute: typeof AuthenticatedLayoutItemFilterItemIdRoute
}

const AuthenticatedLayoutItemFilterRouteChildren: AuthenticatedLayoutItemFilterRouteChildren =
  {
    AuthenticatedLayoutItemFilterItemIdRoute:
      AuthenticatedLayoutItemFilterItemIdRoute,
  }

const AuthenticatedLayoutItemFilterRouteWithChildren =
  AuthenticatedLayoutItemFilterRoute._addFileChildren(
    AuthenticatedLayoutItemFilterRouteChildren,
  )

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutItemFilterRoute: typeof AuthenticatedLayoutItemFilterRouteWithChildren
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutItemFilterRoute:
    AuthenticatedLayoutItemFilterRouteWithChildren,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  InitializeRoute: InitializeRoute,
  LockRoute: LockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
